### PR TITLE
Support for .NET 8.0 is now available, featuring the ability to adjust the waiting time for ping through the exposed TimeMilliseconds.

### PR DESCRIPTION
**Pull request by J0nathan550**
- Added in `.csproj` of all projects in this repo the `.NET 8`. Except the `Example.csproj`
- Updated the libraries for `.NET 8.0` specific
- Changed `Example.cs` (added `try-catch` blocks so that the script will not crash because of server issues).
- Exposed in `SampQuery.cs` `TimeoutMilliseconds` with new summary to it.

### CODE REVIEW

**Comment by justmavi** [comment]
Thank you for your contribution. 

We need non-static TimeoutMilliseconds property. As you know, each instance of the SampQuery class can only work with one server. Thus, non-static TimeoutMilliseconds will allow us to set a custom timeout for each instance. And it will be used as follow...

```csharp
var server = new SampQuery("localhost") { TimeoutMilliseconds = 10000 };
```

**Comment by J0nathan550** [comment]
Sure in few hours I will update my branch! As soon as I get back yo my house :)

**Comment by J0nathan550** [comment]
Sure in few hours I will update my branch! As soon as I get back to my house :)

**Comment by J0nathan550** [comment]
Hello! Branch is updated. 

Updated:

- `Example.cs` to see how `TimeoutMilliseconds` is modifiable.
- `TimeoutMilliseconds` is no longer `static`, but is a property that you can modify for new instance of class. Or at runtime.

**Comment by J0nathan550** [comment]
Now this is fine, second commit was ignored all my changes lol.

**Comment by J0nathan550** [comment]
Hey, when you will update package? 3 weeks passed 😄

**Comment by justmavi** [comment]
Hi.
I planned the release after February.
Do you need this change very urgently?

**Comment by J0nathan550** [comment]
Not that urgently, just thought you could forget about the pull.

**Pull request closed without merging**
